export const IS_PUBLIC_KEY = 'isPublic';

export const REQUEST_ID_HEADER = 'x-request-id';

export const ERROR_CODES = {
  VALIDATION: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  INTERNAL: 'INTERNAL_ERROR',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_EMAIL_NOT_VERIFIED: 'AUTH_EMAIL_NOT_VERIFIED',
  AUTH_EMAIL_ALREADY_EXISTS: 'AUTH_EMAIL_ALREADY_EXISTS',
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_OAUTH_FAILED: 'AUTH_OAUTH_FAILED',
  GROUP_NOT_FOUND: 'GROUP_NOT_FOUND',
  GROUP_FORBIDDEN: 'GROUP_FORBIDDEN',
  INVITE_INVALID: 'INVITE_INVALID',
  INVITE_EXPIRED: 'INVITE_EXPIRED',
  SHARING_NOT_FOUND: 'SHARING_NOT_FOUND',
  SHARING_ALREADY_ACTIVE: 'SHARING_ALREADY_ACTIVE',
  SHARING_EXPIRED: 'SHARING_EXPIRED',
  INVALID_DURATION: 'INVALID_DURATION',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
